### ISSUE TITLE
connection issue to Server 2008R2 and 2012

### ISSUE THREAD

**Issue by voglsafe** [hjgode/rdesktopce_rdp5#2]
seems that there is an issue connecting to SV 2008R2 and 2012/R2. 
was already working but, maybe because of a Windows update, now it isn't. 

client ist'n able to connect, but also doesn't throw any exceptions. 
one symptome is, that the client isn't starting if it tries to connect. changing the ip to an SV2003 server is working. 
another message that appers during etablishing the connection is "socket error". 
both seems to be a problem with the meantions Windows server versions.

**Comment by hjgode** [comment]
Please follow the description at http://www.hjgode.de/wp/2014/03/12/windows-server-2012-rds-and-windows-mobile-connection-error/ exactly. Especially the registry Use512LenPropCert setting etc.
