### ISSUE TITLE
BlackScreen with Windows2012R2 RDS Server

### ISSUE THREAD

**Issue by reckeweg** [hjgode/rdesktopce_rdp5#3]
We connect to an W2012R2 RDS Server we become only a Blackscreen.
On a Windows 2008 RDS Server it is working fine.

We have tried various Resolutions, but nothing changes.

Thanks.

S. Dürkes

**Comment by hjgode** [comment]
rdesktop_ce rdp5 has only be tested to support up to win2008R2 server.
Win20012R2 behaves strange for portrait resolutions and if below 800x600. Therea are also konw issues with only showing background, when switching from the start screen to application view.
